-- Whondo Database Schema
-- Copyright (c) Josh Bassett, www.whondo.com 2025
--
-- Author:  Josh Bassett
-- Updated: 02/06/2025

CREATE TABLE Users (
    uID INT UNIQUE NOT NULL AUTO_INCREMENT,    
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(50) NOT NULL,
    surname VARCHAR(50) NOT NULL,
    age INT NOT NULL,
    occupation VARCHAR(255),
    bio TEXT,
    profilePicture VARCHAR(255),
    verified BOOLEAN,
    PRIMARY KEY (uID)
);

ALTER TABLE Users AUTO_INCREMENT=100;

CREATE TABLE Landlords (
    lID INT UNIQUE NOT NULL AUTO_INCREMENT,
    uID INT UNIQUE NOT NULL,
    PRIMARY KEY (lID),
    FOREIGN KEY (uID) REFERENCES Users ON DELETE CASCADE
);

ALTER TABLE Landlords AUTO_INCREMENT=100;

CREATE TABLE Tenants (
    tID INT UNIQUE NOT NULL AUTO_INCREMENT,
    uID INT UNIQUE NOT NULL,
    PRIMARY KEY (tID),
    FOREIGN KEY (uID) REFERENCES Users ON DELETE CASCADE
);

ALTER TABLE Tenants AUTO_INCREMENT=100;

CREATE TABLE Codes (
    code INT NOT NULL,
    uID INT UNIQUE NOT NULL,
    lifetime DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (uID, lifetime),
    FOREIGN KEY (uID) REFERENCES Users ON DELETE CASCADE 
);

CREATE TABLE Property (
    pID INT UNIQUE NOT NULL AUTO_INCREMENT,
    propType VARCHAR(255) NOT NULL,
    bedrooms INT NOT NULL,
    bathrooms INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    street VARCHAR(255) NOT NULL,
    town VARCHAR(255) NOT NULL,
    county VARCHAR(255) NOT NULL,
    postcode CHAR(7),
    lID INT UNIQUE NOT NULL,
    kID INT UNIQUE NOT NULL,
    PRIMARY KEY (pID),
    FOREIGN KEY (lID) REFERENCES Landlords ON DELETE CASCADE,
    FOREIGN KEY (kID) REFERENCES Keywords ON DELETE CASCADE
);

ALTER TABLE Property AUTO_INCREMENT=100;

CREATE TABLE Keywords (
    kID INT UNIQUE NOT NULL AUTO_INCREMENT
);

ALTER TABLE Keywords AUTO_INCREMENT=100;

CREATE TABLE APIKeys (
    aID INT UNIQUE NOT NULL AUTO_INCREMENT,
    uID INT UNIQUE NOT NULL,
    apiKey VARCHAR(255) NOT NULL,
    PRIMARY KEY (aID),
    FOREIGN KEY (uID) REFERENCES Users
);

ALTER TABLE APIKeys AUTO_INCREMENT=100;