-- Whondo Database Schema
-- Copyright c Whondo.com 2025
--
-- Author:  Josh Bassett
-- Updated: 02/06/2025

DROP TABLE IF EXISTS Landlords;
DROP TABLE IF EXISTS Tenants;
DROP TABLE IF EXISTS Codes;
DROP TABLE IF EXISTS Users;

CREATE TABLE Users (
    uID INT UNIQUE NOT NULL AUTO_INCREMENT,    
    email VARCHAR(255) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    name VARCHAR(50) NOT NULL,
    surname VARCHAR(50) NOT NULL,
    age INT NOT NULL,
    occupation VARCHAR(255),
    bio TEXT,
    profilePicture VARCHAR(255),
    verified BOOLEAN,
    PRIMARY KEY (uID)
);

ALTER TABLE Users AUTO_INCREMENT=100;

CREATE TABLE Landlords (
    lID INT UNIQUE NOT NULL AUTO_INCREMENT,
    uID INT UNIQUE NOT NULL,
    PRIMARY KEY (lID),
    FOREIGN KEY (uID) REFERENCES Users ON DELETE CASCADE
);

ALTER TABLE Landlords AUTO_INCREMENT=100;

CREATE TABLE Tenants (
    tID INT UNIQUE NOT NULL AUTO_INCREMENT,
    uID INT UNIQUE NOT NULL,
    PRIMARY KEY (tID),
    FOREIGN KEY (uID) REFERENCES Users ON DELETE CASCADE
);

ALTER TABLE Tenants AUTO_INCREMENT=100;

CREATE TABLE Codes (
    code INT NOT NULL,
    uID INT UNIQUE NOT NULL,
    lifetime DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (uID, lifetime),
    FOREIGN KEY (uID) REFERENCES Users ON DELETE CASCADE 
);